pipeline:
  build:
    image: node:7
    commands:
      - echo "I'm the standard build step"
      - env

  deploy:
    image: node:7
    commands:
      - echo "I get run when the command is 'deploy'"
      - env
    when:
      event: deploy
